language: node_js
node_js:
  - "lts/*"

services:
  - docker

env:
  global:
    - GROUP=deploy.razee.io
    - VERSION=v1alpha2

jobs:
  include:
   - stage: building images
     name: building amd64 image
     arch: amd64
     script:
       # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
       - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm audit; else npm audit || true; fi
       - npm run lint
       - npm test
       - if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
       - docker build --rm -t "quay.io/razee/remoteresources3:${TRAVIS_COMMIT}-amd64" .
       - if [ -n "${TRAVIS_TAG}" ]; then docker tag quay.io/razee/remoteresources3:${TRAVIS_COMMIT}-amd64 quay.io/razee/remoteresources3:${TRAVIS_TAG}-amd64; fi
       - docker images
       - ./build/process-template.sh kubernetes/RemoteResourceS3/resource.yaml >/tmp/resource.yaml
 
     before_deploy:
       - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io
       
     deploy:
       # Deploy alpha builds
       - provider: script
         script: docker push "quay.io/razee/remoteresources3:${TRAVIS_TAG}-amd64"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
       # Deploy released builds
       - provider: script
         script: docker push "quay.io/razee/remoteresources3:${TRAVIS_TAG}-amd64"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
           
   - name: building ppc64le image
     arch: ppc64le
     script:
       # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
       - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm audit; else npm audit || true; fi
       - npm test
       - if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
       - docker build --rm -t "quay.io/razee/remoteresources3:${TRAVIS_COMMIT}-ppc64le" .
       - if [ -n "${TRAVIS_TAG}" ]; then docker tag quay.io/razee/remoteresources3:${TRAVIS_COMMIT}-ppc64le quay.io/razee/remoteresources3:${TRAVIS_TAG}-ppc64le; fi
       - docker images
       - ./build/process-template.sh kubernetes/RemoteResourceS3/resource.yaml >/tmp/resource.yaml
       
     before_deploy:
       - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io
       
     deploy:
       # Deploy alpha builds
       - provider: script
         script: docker push "quay.io/razee/remoteresources3:${TRAVIS_TAG}-ppc64le"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$

       # Deploy released builds
       - provider: script
         script: docker push "quay.io/razee/remoteresources3:${TRAVIS_TAG}-ppc64le"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
           
   - stage: publish multi-arch image, npm & github release
     arch: amd64
     script:
       - if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
       - ./build/process-template.sh kubernetes/RemoteResourceS3/resource.yaml >/tmp/resource.yaml
       - export DOCKER_CLI_EXPERIMENTAL=enabled 
       - sudo chown -R $USER:$USER /etc/docker/ 
       - if [ -n "${TRAVIS_TAG}" ]; then docker manifest create quay.io/razee/remoteresources3:${TRAVIS_TAG} quay.io/razee/remoteresources3:${TRAVIS_TAG}-amd64 quay.io/razee/remoteresources3:${TRAVIS_TAG}-ppc64le; fi
      
     before_deploy:
       - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io
       
     deploy:
       # Deploy alpha builds
       - provider: script
         script: docker push "quay.io/razee/remoteresources3:${TRAVIS_TAG}"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$

       # Deploy released builds
       - provider: script
         script: docker push "quay.io/razee/remoteresources3:${TRAVIS_TAG}"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
       - provider: releases
         file: /tmp/resource.yaml
         skip_cleanup: true
         api_key: "${GITHUB_TOKEN}"
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
       - provider: npm
         email: "${NPMJS_EMAIL}"
         api_key: "${NPMJS_API_KEY}"
         name: "${TRAVIS_TAG}"
         skip_cleanup: true
         on:
           tags: true
           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
